# Generated by Django 4.0.4 on 2022-04-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_id', models.IntegerField()),
                ('created_at', models.DateTimeField(verbose_name='Data de Criacao')),
                ('total', models.FloatField(verbose_name='Total venda')),
                ('status', models.CharField(max_length=50, verbose_name='Status Venda')),
                ('products_count', models.IntegerField(verbose_name='Quantidade de produtos')),
                ('state', models.CharField(max_length=50, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'db_table': 'sales',
            },
        ),
    ]
