# Generated by Django 4.0.4 on 2022-04-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_id',
            field=models.IntegerField(unique=True),
        ),
    ]
