# Generated by Django 4.0.4 on 2022-05-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sale_sale_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='id',
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
